Repository Ullaakut/Bloggo, pull requests merged in 2018-09, with the labels that each got.

#71 Config improvements
  Gopkg.lock
  README.md
  bloggo.go
  config.go
  controller/auth.go
  data/sql/blog_posts.sql
  data/sql/users.sql
  docker-compose.yml
  images/docker-config.png
  service/access.go
  service/access_test.go
  service/token.go
  service/token_test.go
Labels: Documentation, Feature

#74 Hash passwords (#70)
  .gitignore
  .travis.yml
  Gopkg.lock
  README.md
  bloggo.go
  config.go
  controller/user.go
  controller/user_test.go
  godoc.go
  service/hasher.go
  service/hasher_test.go
  service/token.go
  service/token_test.go
Labels: Backend, Feature

#81 Add godoc badge to README.md
  README.md
  godoc.go
Labels: Documentation, Improvement

#82 Fix HasherComparer interface
  service/hasher.go
Labels: Backend, Improvement

#83 Grid layout (#72)
  .gitignore
  app/grid.scss
  app/index.html
Labels: Feature, Front-end

#84 Dockerize frontend & deploy it with nginx (#50) (#69)
  app/Dockerfile
  app/nginx/nginx.conf
  docker-compose.yml
Labels: Feature, Front-end, Tooling

#85 Validate configuration (#73)
  bloggo.go
  config.go
Labels: Backend, Improvement

#87 Add README.md files in subfolders (#86)
  README.md
  app/README.md
  blueprints/README.md
  data/README.md
  test/README.md
Labels: Documentation, Improvement
